---
deployment:
  tasks:
    - export DEPLOYPATH=/home/<your_cpanel_username>/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - /bin/cp -R dist/* $DEPLOYPATH/
