---
deployment:
  tasks:
    - export DEPLOYPATH=/home/<cpanel-username>/public_html
    - /bin/rm -rf $DEPLOYPATH/*
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - /bin/cp -R build/* $DEPLOYPATH/
